package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1



/**
 * Amonestados generated by hbm2java
 */
public class Amonestados  implements java.io.Serializable {


     private Integer idAmonestados;
     private Jugadores jugadores;
     private Partidos partidos;
     private Integer amarillas;
     private Integer rojas;

    public Amonestados() {
    }

    public Amonestados(Jugadores jugadores, Partidos partidos, Integer amarillas, Integer rojas) {
       this.jugadores = jugadores;
       this.partidos = partidos;
       this.amarillas = amarillas;
       this.rojas = rojas;
    }
   
    public Integer getIdAmonestados() {
        return this.idAmonestados;
    }
    
    public void setIdAmonestados(Integer idAmonestados) {
        this.idAmonestados = idAmonestados;
    }
    public Jugadores getJugadores() {
        return this.jugadores;
    }
    
    public void setJugadores(Jugadores jugadores) {
        this.jugadores = jugadores;
    }
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }
    public Integer getAmarillas() {
        return this.amarillas;
    }
    
    public void setAmarillas(Integer amarillas) {
        this.amarillas = amarillas;
    }
    public Integer getRojas() {
        return this.rojas;
    }
    
    public void setRojas(Integer rojas) {
        this.rojas = rojas;
    }




}


