package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer idCategorias;
     private Integer categoria;
     private String categoriaObserv;
     private Set<CategoriasTorneos> categoriasTorneoses = new HashSet<CategoriasTorneos>(0);
     private Set<LigaCate> ligaCates = new HashSet<LigaCate>(0);
     private Set<Equipos> equiposes = new HashSet<Equipos>(0);
     private Set<Clasificaciones> clasificacioneses = new HashSet<Clasificaciones>(0);
     private Set<Partidos> partidoses = new HashSet<Partidos>(0);

    public Categorias() {
    }

    public Categorias(Integer categoria, String categoriaObserv, Set<CategoriasTorneos> categoriasTorneoses, Set<LigaCate> ligaCates, Set<Equipos> equiposes, Set<Clasificaciones> clasificacioneses, Set<Partidos> partidoses) {
       this.categoria = categoria;
       this.categoriaObserv = categoriaObserv;
       this.categoriasTorneoses = categoriasTorneoses;
       this.ligaCates = ligaCates;
       this.equiposes = equiposes;
       this.clasificacioneses = clasificacioneses;
       this.partidoses = partidoses;
    }
   
    public Integer getIdCategorias() {
        return this.idCategorias;
    }
    
    public void setIdCategorias(Integer idCategorias) {
        this.idCategorias = idCategorias;
    }
    public Integer getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Integer categoria) {
        this.categoria = categoria;
    }
    public String getCategoriaObserv() {
        return this.categoriaObserv;
    }
    
    public void setCategoriaObserv(String categoriaObserv) {
        this.categoriaObserv = categoriaObserv;
    }
    public Set<CategoriasTorneos> getCategoriasTorneoses() {
        return this.categoriasTorneoses;
    }
    
    public void setCategoriasTorneoses(Set<CategoriasTorneos> categoriasTorneoses) {
        this.categoriasTorneoses = categoriasTorneoses;
    }
    public Set<LigaCate> getLigaCates() {
        return this.ligaCates;
    }
    
    public void setLigaCates(Set<LigaCate> ligaCates) {
        this.ligaCates = ligaCates;
    }
    public Set<Equipos> getEquiposes() {
        return this.equiposes;
    }
    
    public void setEquiposes(Set<Equipos> equiposes) {
        this.equiposes = equiposes;
    }
    public Set<Clasificaciones> getClasificacioneses() {
        return this.clasificacioneses;
    }
    
    public void setClasificacioneses(Set<Clasificaciones> clasificacioneses) {
        this.clasificacioneses = clasificacioneses;
    }
    public Set<Partidos> getPartidoses() {
        return this.partidoses;
    }
    
    public void setPartidoses(Set<Partidos> partidoses) {
        this.partidoses = partidoses;
    }




}


