package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1



/**
 * CategoriasTorneos generated by hbm2java
 */
public class CategoriasTorneos  implements java.io.Serializable {


     private Integer idcategoriasTorneos;
     private Categorias categorias;
     private Torneos torneos;

    public CategoriasTorneos() {
    }

    public CategoriasTorneos(Categorias categorias, Torneos torneos) {
       this.categorias = categorias;
       this.torneos = torneos;
    }
   
    public Integer getIdcategoriasTorneos() {
        return this.idcategoriasTorneos;
    }
    
    public void setIdcategoriasTorneos(Integer idcategoriasTorneos) {
        this.idcategoriasTorneos = idcategoriasTorneos;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Torneos getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Torneos torneos) {
        this.torneos = torneos;
    }




}


