package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1



/**
 * Clasificaciones generated by hbm2java
 */
public class Clasificaciones  implements java.io.Serializable {


     private Integer idclasificaciones;
     private Categorias categorias;
     private Equipos equipos;
     private Liga liga;
     private Torneos torneos;
     private Zonas zonas;
     private Integer pj;
     private Integer pe;
     private Integer pp;
     private Integer pg;
     private Integer gf;
     private Integer gc;
     private Integer dg;
     private Integer puntos;

    public Clasificaciones() {
    }

    public Clasificaciones(Categorias categorias, Equipos equipos, Liga liga, Torneos torneos, Zonas zonas, Integer pj, Integer pe, Integer pp, Integer pg, Integer gf, Integer gc, Integer dg, Integer puntos) {
       this.categorias = categorias;
       this.equipos = equipos;
       this.liga = liga;
       this.torneos = torneos;
       this.zonas = zonas;
       this.pj = pj;
       this.pe = pe;
       this.pp = pp;
       this.pg = pg;
       this.gf = gf;
       this.gc = gc;
       this.dg = dg;
       this.puntos = puntos;
    }
   
    public Integer getIdclasificaciones() {
        return this.idclasificaciones;
    }
    
    public void setIdclasificaciones(Integer idclasificaciones) {
        this.idclasificaciones = idclasificaciones;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public Torneos getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Torneos torneos) {
        this.torneos = torneos;
    }
    public Zonas getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Zonas zonas) {
        this.zonas = zonas;
    }
    public Integer getPj() {
        return this.pj;
    }
    
    public void setPj(Integer pj) {
        this.pj = pj;
    }
    public Integer getPe() {
        return this.pe;
    }
    
    public void setPe(Integer pe) {
        this.pe = pe;
    }
    public Integer getPp() {
        return this.pp;
    }
    
    public void setPp(Integer pp) {
        this.pp = pp;
    }
    public Integer getPg() {
        return this.pg;
    }
    
    public void setPg(Integer pg) {
        this.pg = pg;
    }
    public Integer getGf() {
        return this.gf;
    }
    
    public void setGf(Integer gf) {
        this.gf = gf;
    }
    public Integer getGc() {
        return this.gc;
    }
    
    public void setGc(Integer gc) {
        this.gc = gc;
    }
    public Integer getDg() {
        return this.dg;
    }
    
    public void setDg(Integer dg) {
        this.dg = dg;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }




}


