package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer idEquipos;
     private Categorias categorias;
     private Zonas zonas;
     private String equipoNombre;
     private String equipoLogo;
     private Integer equipoestado;
     private Set<LigaEquipo> ligaEquipos = new HashSet<LigaEquipo>(0);
     private Set<JugadoresEquipos> jugadoresEquiposes = new HashSet<JugadoresEquipos>(0);
     private Set<Clasificaciones> clasificacioneses = new HashSet<Clasificaciones>(0);
     private Set<Partidos> partidosesForPequipoUno = new HashSet<Partidos>(0);
     private Set<Partidos> partidosesForPequipoDos = new HashSet<Partidos>(0);

    public Equipos() {
    }

    public Equipos(Categorias categorias, Zonas zonas, String equipoNombre, String equipoLogo, Integer equipoestado, Set<LigaEquipo> ligaEquipos, Set<JugadoresEquipos> jugadoresEquiposes, Set<Clasificaciones> clasificacioneses, Set<Partidos> partidosesForPequipoUno, Set<Partidos> partidosesForPequipoDos) {
       this.categorias = categorias;
       this.zonas = zonas;
       this.equipoNombre = equipoNombre;
       this.equipoLogo = equipoLogo;
       this.equipoestado = equipoestado;
       this.ligaEquipos = ligaEquipos;
       this.jugadoresEquiposes = jugadoresEquiposes;
       this.clasificacioneses = clasificacioneses;
       this.partidosesForPequipoUno = partidosesForPequipoUno;
       this.partidosesForPequipoDos = partidosesForPequipoDos;
    }
   
    public Integer getIdEquipos() {
        return this.idEquipos;
    }
    
    public void setIdEquipos(Integer idEquipos) {
        this.idEquipos = idEquipos;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Zonas getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Zonas zonas) {
        this.zonas = zonas;
    }
    public String getEquipoNombre() {
        return this.equipoNombre;
    }
    
    public void setEquipoNombre(String equipoNombre) {
        this.equipoNombre = equipoNombre;
    }
    public String getEquipoLogo() {
        return this.equipoLogo;
    }
    
    public void setEquipoLogo(String equipoLogo) {
        this.equipoLogo = equipoLogo;
    }
    public Integer getEquipoestado() {
        return this.equipoestado;
    }
    
    public void setEquipoestado(Integer equipoestado) {
        this.equipoestado = equipoestado;
    }
    public Set<LigaEquipo> getLigaEquipos() {
        return this.ligaEquipos;
    }
    
    public void setLigaEquipos(Set<LigaEquipo> ligaEquipos) {
        this.ligaEquipos = ligaEquipos;
    }
    public Set<JugadoresEquipos> getJugadoresEquiposes() {
        return this.jugadoresEquiposes;
    }
    
    public void setJugadoresEquiposes(Set<JugadoresEquipos> jugadoresEquiposes) {
        this.jugadoresEquiposes = jugadoresEquiposes;
    }
    public Set<Clasificaciones> getClasificacioneses() {
        return this.clasificacioneses;
    }
    
    public void setClasificacioneses(Set<Clasificaciones> clasificacioneses) {
        this.clasificacioneses = clasificacioneses;
    }
    public Set<Partidos> getPartidosesForPequipoUno() {
        return this.partidosesForPequipoUno;
    }
    
    public void setPartidosesForPequipoUno(Set<Partidos> partidosesForPequipoUno) {
        this.partidosesForPequipoUno = partidosesForPequipoUno;
    }
    public Set<Partidos> getPartidosesForPequipoDos() {
        return this.partidosesForPequipoDos;
    }
    
    public void setPartidosesForPequipoDos(Set<Partidos> partidosesForPequipoDos) {
        this.partidosesForPequipoDos = partidosesForPequipoDos;
    }




}


