package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1



/**
 * Goleadores generated by hbm2java
 */
public class Goleadores  implements java.io.Serializable {


     private Integer idGoleadores;
     private Jugadores jugadores;
     private Partidos partidos;
     private Integer cantGoles;

    public Goleadores() {
    }

    public Goleadores(Jugadores jugadores, Partidos partidos, Integer cantGoles) {
       this.jugadores = jugadores;
       this.partidos = partidos;
       this.cantGoles = cantGoles;
    }
   
    public Integer getIdGoleadores() {
        return this.idGoleadores;
    }
    
    public void setIdGoleadores(Integer idGoleadores) {
        this.idGoleadores = idGoleadores;
    }
    public Jugadores getJugadores() {
        return this.jugadores;
    }
    
    public void setJugadores(Jugadores jugadores) {
        this.jugadores = jugadores;
    }
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }
    public Integer getCantGoles() {
        return this.cantGoles;
    }
    
    public void setCantGoles(Integer cantGoles) {
        this.cantGoles = cantGoles;
    }




}


