package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private Integer idJugadores;
     private String jugadorNumSocio;
     private String jugadorDni;
     private String jugadorApellido;
     private String jugadorNombre;
     private String jugadoresFoto;
     private Integer jugadoresEstado;
     private Set<JugadoresEquipos> jugadoresEquiposes = new HashSet<JugadoresEquipos>(0);
     private Set<Goleadores> goleadoreses = new HashSet<Goleadores>(0);
     private Set<Amonestados> amonestadoses = new HashSet<Amonestados>(0);

    public Jugadores() {
    }

    public Jugadores(String jugadorNumSocio, String jugadorDni, String jugadorApellido, String jugadorNombre, String jugadoresFoto, Integer jugadoresEstado, Set<JugadoresEquipos> jugadoresEquiposes, Set<Goleadores> goleadoreses, Set<Amonestados> amonestadoses) {
       this.jugadorNumSocio = jugadorNumSocio;
       this.jugadorDni = jugadorDni;
       this.jugadorApellido = jugadorApellido;
       this.jugadorNombre = jugadorNombre;
       this.jugadoresFoto = jugadoresFoto;
       this.jugadoresEstado = jugadoresEstado;
       this.jugadoresEquiposes = jugadoresEquiposes;
       this.goleadoreses = goleadoreses;
       this.amonestadoses = amonestadoses;
    }
   
    public Integer getIdJugadores() {
        return this.idJugadores;
    }
    
    public void setIdJugadores(Integer idJugadores) {
        this.idJugadores = idJugadores;
    }
    public String getJugadorNumSocio() {
        return this.jugadorNumSocio;
    }
    
    public void setJugadorNumSocio(String jugadorNumSocio) {
        this.jugadorNumSocio = jugadorNumSocio;
    }
    public String getJugadorDni() {
        return this.jugadorDni;
    }
    
    public void setJugadorDni(String jugadorDni) {
        this.jugadorDni = jugadorDni;
    }
    public String getJugadorApellido() {
        return this.jugadorApellido;
    }
    
    public void setJugadorApellido(String jugadorApellido) {
        this.jugadorApellido = jugadorApellido;
    }
    public String getJugadorNombre() {
        return this.jugadorNombre;
    }
    
    public void setJugadorNombre(String jugadorNombre) {
        this.jugadorNombre = jugadorNombre;
    }
    public String getJugadoresFoto() {
        return this.jugadoresFoto;
    }
    
    public void setJugadoresFoto(String jugadoresFoto) {
        this.jugadoresFoto = jugadoresFoto;
    }
    public Integer getJugadoresEstado() {
        return this.jugadoresEstado;
    }
    
    public void setJugadoresEstado(Integer jugadoresEstado) {
        this.jugadoresEstado = jugadoresEstado;
    }
    public Set<JugadoresEquipos> getJugadoresEquiposes() {
        return this.jugadoresEquiposes;
    }
    
    public void setJugadoresEquiposes(Set<JugadoresEquipos> jugadoresEquiposes) {
        this.jugadoresEquiposes = jugadoresEquiposes;
    }
    public Set<Goleadores> getGoleadoreses() {
        return this.goleadoreses;
    }
    
    public void setGoleadoreses(Set<Goleadores> goleadoreses) {
        this.goleadoreses = goleadoreses;
    }
    public Set<Amonestados> getAmonestadoses() {
        return this.amonestadoses;
    }
    
    public void setAmonestadoses(Set<Amonestados> amonestadoses) {
        this.amonestadoses = amonestadoses;
    }




}


