package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1



/**
 * LigaEquipo generated by hbm2java
 */
public class LigaEquipo  implements java.io.Serializable {


     private Integer idligaEquipo;
     private Equipos equipos;
     private Liga liga;

    public LigaEquipo() {
    }

    public LigaEquipo(Equipos equipos, Liga liga) {
       this.equipos = equipos;
       this.liga = liga;
    }
   
    public Integer getIdligaEquipo() {
        return this.idligaEquipo;
    }
    
    public void setIdligaEquipo(Integer idligaEquipo) {
        this.idligaEquipo = idligaEquipo;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }




}


