package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1



/**
 * LigaCate generated by hbm2java
 */
public class LigaCate  implements java.io.Serializable {


     private int idcateTorneo;
     private Categorias categorias;
     private Liga liga;

    public LigaCate() {
    }

	
    public LigaCate(int idcateTorneo) {
        this.idcateTorneo = idcateTorneo;
    }
    public LigaCate(int idcateTorneo, Categorias categorias, Liga liga) {
       this.idcateTorneo = idcateTorneo;
       this.categorias = categorias;
       this.liga = liga;
    }
   
    public int getIdcateTorneo() {
        return this.idcateTorneo;
    }
    
    public void setIdcateTorneo(int idcateTorneo) {
        this.idcateTorneo = idcateTorneo;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }




}


