package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidos generated by hbm2java
 */
public class Partidos  implements java.io.Serializable {


     private Integer idPartidos;
     private Categorias categorias;
     private Equipos equiposByPequipoUno;
     private Equipos equiposByPequipoDos;
     private Torneos torneos;
     private Zonas zonas;
     private Date pfecha;
     private Integer presultEquiUno;
     private Integer presultEquiDos;
     private Set<Goleadores> goleadoreses = new HashSet<Goleadores>(0);
     private Set<Amonestados> amonestadoses = new HashSet<Amonestados>(0);

    public Partidos() {
    }

    public Partidos(Categorias categorias, Equipos equiposByPequipoUno, Equipos equiposByPequipoDos, Torneos torneos, Zonas zonas, Date pfecha, Integer presultEquiUno, Integer presultEquiDos, Set<Goleadores> goleadoreses, Set<Amonestados> amonestadoses) {
       this.categorias = categorias;
       this.equiposByPequipoUno = equiposByPequipoUno;
       this.equiposByPequipoDos = equiposByPequipoDos;
       this.torneos = torneos;
       this.zonas = zonas;
       this.pfecha = pfecha;
       this.presultEquiUno = presultEquiUno;
       this.presultEquiDos = presultEquiDos;
       this.goleadoreses = goleadoreses;
       this.amonestadoses = amonestadoses;
    }
   
    public Integer getIdPartidos() {
        return this.idPartidos;
    }
    
    public void setIdPartidos(Integer idPartidos) {
        this.idPartidos = idPartidos;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Equipos getEquiposByPequipoUno() {
        return this.equiposByPequipoUno;
    }
    
    public void setEquiposByPequipoUno(Equipos equiposByPequipoUno) {
        this.equiposByPequipoUno = equiposByPequipoUno;
    }
    public Equipos getEquiposByPequipoDos() {
        return this.equiposByPequipoDos;
    }
    
    public void setEquiposByPequipoDos(Equipos equiposByPequipoDos) {
        this.equiposByPequipoDos = equiposByPequipoDos;
    }
    public Torneos getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Torneos torneos) {
        this.torneos = torneos;
    }
    public Zonas getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Zonas zonas) {
        this.zonas = zonas;
    }
    public Date getPfecha() {
        return this.pfecha;
    }
    
    public void setPfecha(Date pfecha) {
        this.pfecha = pfecha;
    }
    public Integer getPresultEquiUno() {
        return this.presultEquiUno;
    }
    
    public void setPresultEquiUno(Integer presultEquiUno) {
        this.presultEquiUno = presultEquiUno;
    }
    public Integer getPresultEquiDos() {
        return this.presultEquiDos;
    }
    
    public void setPresultEquiDos(Integer presultEquiDos) {
        this.presultEquiDos = presultEquiDos;
    }
    public Set<Goleadores> getGoleadoreses() {
        return this.goleadoreses;
    }
    
    public void setGoleadoreses(Set<Goleadores> goleadoreses) {
        this.goleadoreses = goleadoreses;
    }
    public Set<Amonestados> getAmonestadoses() {
        return this.amonestadoses;
    }
    
    public void setAmonestadoses(Set<Amonestados> amonestadoses) {
        this.amonestadoses = amonestadoses;
    }




}


