package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Torneos generated by hbm2java
 */
public class Torneos  implements java.io.Serializable {


     private Integer idtorneos;
     private Liga liga;
     private String torneoNombre;
     private String torneoTipo;
     private Integer torneosEstado;
     private Set<TorneosZonas> torneosZonases = new HashSet<TorneosZonas>(0);
     private Set<Partidos> partidoses = new HashSet<Partidos>(0);
     private Set<Clasificaciones> clasificacioneses = new HashSet<Clasificaciones>(0);
     private Set<CategoriasTorneos> categoriasTorneoses = new HashSet<CategoriasTorneos>(0);

    public Torneos() {
    }

    public Torneos(Liga liga, String torneoNombre, String torneoTipo, Integer torneosEstado, Set<TorneosZonas> torneosZonases, Set<Partidos> partidoses, Set<Clasificaciones> clasificacioneses, Set<CategoriasTorneos> categoriasTorneoses) {
       this.liga = liga;
       this.torneoNombre = torneoNombre;
       this.torneoTipo = torneoTipo;
       this.torneosEstado = torneosEstado;
       this.torneosZonases = torneosZonases;
       this.partidoses = partidoses;
       this.clasificacioneses = clasificacioneses;
       this.categoriasTorneoses = categoriasTorneoses;
    }
   
    public Integer getIdtorneos() {
        return this.idtorneos;
    }
    
    public void setIdtorneos(Integer idtorneos) {
        this.idtorneos = idtorneos;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public String getTorneoNombre() {
        return this.torneoNombre;
    }
    
    public void setTorneoNombre(String torneoNombre) {
        this.torneoNombre = torneoNombre;
    }
    public String getTorneoTipo() {
        return this.torneoTipo;
    }
    
    public void setTorneoTipo(String torneoTipo) {
        this.torneoTipo = torneoTipo;
    }
    public Integer getTorneosEstado() {
        return this.torneosEstado;
    }
    
    public void setTorneosEstado(Integer torneosEstado) {
        this.torneosEstado = torneosEstado;
    }
    public Set<TorneosZonas> getTorneosZonases() {
        return this.torneosZonases;
    }
    
    public void setTorneosZonases(Set<TorneosZonas> torneosZonases) {
        this.torneosZonases = torneosZonases;
    }
    public Set<Partidos> getPartidoses() {
        return this.partidoses;
    }
    
    public void setPartidoses(Set<Partidos> partidoses) {
        this.partidoses = partidoses;
    }
    public Set<Clasificaciones> getClasificacioneses() {
        return this.clasificacioneses;
    }
    
    public void setClasificacioneses(Set<Clasificaciones> clasificacioneses) {
        this.clasificacioneses = clasificacioneses;
    }
    public Set<CategoriasTorneos> getCategoriasTorneoses() {
        return this.categoriasTorneoses;
    }
    
    public void setCategoriasTorneoses(Set<CategoriasTorneos> categoriasTorneoses) {
        this.categoriasTorneoses = categoriasTorneoses;
    }




}


