package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1



/**
 * TorneosZonas generated by hbm2java
 */
public class TorneosZonas  implements java.io.Serializable {


     private Integer idcateTorneos;
     private Torneos torneos;
     private Zonas zonas;

    public TorneosZonas() {
    }

    public TorneosZonas(Torneos torneos, Zonas zonas) {
       this.torneos = torneos;
       this.zonas = zonas;
    }
   
    public Integer getIdcateTorneos() {
        return this.idcateTorneos;
    }
    
    public void setIdcateTorneos(Integer idcateTorneos) {
        this.idcateTorneos = idcateTorneos;
    }
    public Torneos getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Torneos torneos) {
        this.torneos = torneos;
    }
    public Zonas getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Zonas zonas) {
        this.zonas = zonas;
    }




}


