package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer usuCodigo;
     private Liga liga;
     private String usuNombre;
     private String usuApellido;
     private String usuLogin;
     private String usuPassword;
     private Set<UsuRol> usuRols = new HashSet<UsuRol>(0);

    public Usuarios() {
    }

    public Usuarios(Liga liga, String usuNombre, String usuApellido, String usuLogin, String usuPassword, Set<UsuRol> usuRols) {
       this.liga = liga;
       this.usuNombre = usuNombre;
       this.usuApellido = usuApellido;
       this.usuLogin = usuLogin;
       this.usuPassword = usuPassword;
       this.usuRols = usuRols;
    }
   
    public Integer getUsuCodigo() {
        return this.usuCodigo;
    }
    
    public void setUsuCodigo(Integer usuCodigo) {
        this.usuCodigo = usuCodigo;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuApellido() {
        return this.usuApellido;
    }
    
    public void setUsuApellido(String usuApellido) {
        this.usuApellido = usuApellido;
    }
    public String getUsuLogin() {
        return this.usuLogin;
    }
    
    public void setUsuLogin(String usuLogin) {
        this.usuLogin = usuLogin;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }
    public Set<UsuRol> getUsuRols() {
        return this.usuRols;
    }
    
    public void setUsuRols(Set<UsuRol> usuRols) {
        this.usuRols = usuRols;
    }




}


