package pojos;
// Generated 26/10/2017 10:10:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zonas generated by hbm2java
 */
public class Zonas  implements java.io.Serializable {


     private Integer idZonas;
     private String zonasNombre;
     private String zonasDetalle;
     private Set<Partidos> partidoses = new HashSet<Partidos>(0);
     private Set<Equipos> equiposes = new HashSet<Equipos>(0);
     private Set<Clasificaciones> clasificacioneses = new HashSet<Clasificaciones>(0);
     private Set<TorneosZonas> torneosZonases = new HashSet<TorneosZonas>(0);

    public Zonas() {
    }

    public Zonas(String zonasNombre, String zonasDetalle, Set<Partidos> partidoses, Set<Equipos> equiposes, Set<Clasificaciones> clasificacioneses, Set<TorneosZonas> torneosZonases) {
       this.zonasNombre = zonasNombre;
       this.zonasDetalle = zonasDetalle;
       this.partidoses = partidoses;
       this.equiposes = equiposes;
       this.clasificacioneses = clasificacioneses;
       this.torneosZonases = torneosZonases;
    }
   
    public Integer getIdZonas() {
        return this.idZonas;
    }
    
    public void setIdZonas(Integer idZonas) {
        this.idZonas = idZonas;
    }
    public String getZonasNombre() {
        return this.zonasNombre;
    }
    
    public void setZonasNombre(String zonasNombre) {
        this.zonasNombre = zonasNombre;
    }
    public String getZonasDetalle() {
        return this.zonasDetalle;
    }
    
    public void setZonasDetalle(String zonasDetalle) {
        this.zonasDetalle = zonasDetalle;
    }
    public Set<Partidos> getPartidoses() {
        return this.partidoses;
    }
    
    public void setPartidoses(Set<Partidos> partidoses) {
        this.partidoses = partidoses;
    }
    public Set<Equipos> getEquiposes() {
        return this.equiposes;
    }
    
    public void setEquiposes(Set<Equipos> equiposes) {
        this.equiposes = equiposes;
    }
    public Set<Clasificaciones> getClasificacioneses() {
        return this.clasificacioneses;
    }
    
    public void setClasificacioneses(Set<Clasificaciones> clasificacioneses) {
        this.clasificacioneses = clasificacioneses;
    }
    public Set<TorneosZonas> getTorneosZonases() {
        return this.torneosZonases;
    }
    
    public void setTorneosZonases(Set<TorneosZonas> torneosZonases) {
        this.torneosZonases = torneosZonases;
    }




}


